variable "RG_name" {}
variable "location" {}
variable "Vnet_name" {}
variable "subnet1_name" {}
variable "subnet2_name" {}
variable "pip_name" {}
variable "allocation_method" {}
variable "bastion_name" {}
variable "ip_config_name_bastion" {}
variable "address_space" {}
variable "address_prefixes1" {}
variable "address_prefixes2" {}
variable "nic1_name" {}
variable "ip_config_name_nic1" {}
variable "nic2_name" {}
variable "ip_config_name_nic2" {}
variable "vm1_size" {}
variable "vm2_size" {}
variable "vm1_name" {}
variable "vm2_name" {}
variable "admin_username1" {}
variable "admin_password1" {}
variable "admin_username2" {}
variable "admin_password2" {}
variable "os_disk_caching1" {}
variable "os_disk_caching2" {}
variable "storage_account_type1" {}
variable "storage_account_type2" {}
variable "image_publisher1" {}
variable "image_publisher2" {}
variable "image_offer1" {}
variable "image_offer2" {}
variable "image_sku1" {}
variable "image_sku2" {}
variable "image_version1" {}
variable "image_version2" {}
variable "pip_allocation" {}
variable "lb_name" {}
variable "frontend_ip_config_name" {}
variable "backendPool_name" {}
variable "lbRule_name" {}
variable "protocol" {}
variable "frontend_port" {}
variable "backend_port" {}
variable "lb_probe_name" {}
variable "lb_probe_port" {}
variable "LBpip_name" {}
variable "BASTIONpip_name" {}
variable "nsg_name" {}
variable "security_rule_name" {}
variable "priority" {}
variable "direction" {}
variable "access" {}
variable "source_port_range" {}
variable "destination_port_range" {}
variable "source_address_prefix" {}
variable "destination_address_prefix" {}

